# Generated by Django 3.1.5 on 2021-02-12 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0003_auto_20210211_2039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='fondo',
            name='tipo',
        ),
        migrations.AddField(
            model_name='log',
            name='valorBTC',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='log',
            name='valorDAI',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fondo',
            name='plataforma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Registro.plataforma'),
        ),
    ]
