# Generated by Django 3.1.5 on 2021-02-14 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0005_auto_20210214_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
