# Generated by Django 3.1.5 on 2021-02-26 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0007_auto_20210216_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Registro.tipo_log'),
        ),
    ]
