# Generated by Django 3.1.5 on 2021-02-26 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0008_auto_20210225_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='categoria_dest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destino', to='Registro.categoria'),
        ),
        migrations.AddField(
            model_name='log',
            name='categoria_origen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='origen', to='Registro.categoria'),
        ),
    ]
