# Generated by Django 3.1.5 on 2021-02-26 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0009_auto_20210226_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='valorDAI',
        ),
        migrations.AddField(
            model_name='log',
            name='comision',
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='porcentaje_fijo',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='valorUSDC',
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='moneda_origen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='origen', to='Registro.moneda'),
        ),
        migrations.AlterField(
            model_name='log',
            name='valorBTC',
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
        migrations.CreateModel(
            name='Log_Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_dest', models.DecimalField(decimal_places=10, max_digits=20, null=True)),
                ('precio', models.DecimalField(decimal_places=10, max_digits=20, null=True)),
                ('moneda_com', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comision', to='Registro.moneda')),
                ('moneda_dest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destino', to='Registro.moneda')),
            ],
        ),
    ]
